### ISSUE TITLE
Some RPKMs are less than 0 after correcting batch effects

### ISSUE THREAD

**Issue by qwangmsk** [jtleek/svaseq#1]
Hello Jeff, 

I am using your SVASEQ to remove batch effect. It worked pretty well on my data. One issue is that it resulted in RPKMs less than 0 for some genes. I wonder what you suggest to deal with minus RPKMs, because I hope unexpressed or low expressed genes to have a zero or a positive value close to zero, to ease clinical explanation.  

Thanks and looks forward to your response.
Qingguo

**Comment by jtleek** [comment]
Hi Qinqguo,

Glad that it worked well! One thing to keep in mind is that the log2 transform is applied to the data before the svs are calculated, so that may be one reason you see the negative numbers. Another thing that should happen is that you should get sv estimates out, but then they can be included in a model (for example DEseq/edgeR using the original, non-zero data. 

If you regress the svs out to get a "clean" data set then downstream analyses may be biased, so you might just consider using them as adjustment covariates. 

Best

Jeff
