### ISSUE TITLE
problem with running SVA

### ISSUE THREAD

**Issue by qwangmsk** [jtleek/svaseq#3]
Hi Jeff,

I tried to apply SVA to a set of data but encountered some problems. If I ran command "ComBat(dat=data, batch=batch, mod=mod1)", I received this error:

Found 3 batches
Found 4  categorical covariate(s)
Standardizing Data across genes
Error in solve.default(t(design) %*% design) : 
  Lapack routine dgesv: system is exactly singular: U[4,4] = 0

On the same data, if I executed command "svobj = sva(data,mod1,mod0)", I got a different error:

Number of significant surrogate variables is:  86 
Error in dat %_% (Id - mod %_% solve(t(mod) %_% mod) %_% t(mod)) : 
  requires numeric/complex matrix/vector arguments

I spent quite some time on googling solutions but is not able to get around it so far. Any idea of what went wrong?

Thanks,
Qingguo

**Comment by farshadf** [comment]
Hi Qingguo,

I hope Jeff doesn't mind if I help a bit here!

The problem you have is probably because of the way you have organized the data. The error messages mean that the function used in the R cannot be correctly applied. I suggest going through the vignettes provided with the package, and compare your dataset's structure with the one used in the vignettes. It should be pretty straight forward from that point.

The second error very probably points to having non-numeric data in your dataset. Make sure everything is numeric, which can be checked through 

`typeof (dataset)`

It should return numeric.

You can see the details by 

`str (dataset)`

as well.

Cheers,
Farshad

**Comment by qwangmsk** [comment]
My dataset is numeric. I am not sure if it was organization of data that caused error, as I was able to run the code on a smaller dataset organized in a similar way. But thanks for your suggestions.

Qingguo

**Comment by qwangmsk** [comment]
My problem was fixed. It was caused in part by the data. Thanks Farshad for the help.

Qingguo

**Comment by amoltej** [comment]
Hello qwangmsk, 

I am also getting the same error. can you please tell me how so solve it. 
Thank you!
AMoL

**Comment by zhenyisong** [comment]
@amoltej and @qwangmsk How did you solve the problem? What kind of further step should we transform the original data to carry out the svaseq?

**Comment by qwangmsk** [comment]
I wrote a wrapper for combat: https://github.com/mskcc/RNAseqDB/blob/master/run-combat.R. The code is public. You can directly run this program.

**Comment by zhenyisong** [comment]
@qwangmsk  Thanks for your speed responding. I read your code and if my understanding is correct, you added the constant (5)  or similiar filter to shadow the low expression genes to the raw count data and transformed raw count data into log formatted matrix. But my intention is to perform the downstream analysis by Limma package which requires that the input data is count data and uses its inner function VOOM to transform the count data to another form with the weight. So, the output of your wrapper script cannot be used directly for limma analysis. Does your have extra step to re-scale the data from your wrapper and use voom-limma procedure? 

Because I called the svaseq() function in SVA package, the thrown-out error said that " Lapack routine dgesv: system is exactly singular: U[1,1] = 0".  After googling, the error may be related to "sovle" function in matrix decomposition. I used the filter ( added the constant and retained genes with sd > 0.2), but still failed to perform the svaseq and get the cleaned the data. Any suggestions? Thanks in advance.

**Comment by royfrancis** [comment]
I got the same stupid error and I solved it by converting the `data.frame` to a `matrix` datatype.

When you have something like this:
`ComBat(dat=data, batch=batch, mod=mod1)`

Use this instead:
`ComBat(dat=as.matrix(data), batch=batch, mod=mod1)`

**Comment by maggie-fu** [comment]
Hi,
I recently encountered the same problem as I tried to correct for the batch effect with ComBat. I am working with Illumina methylation data. I wanted to eliminate the effect of array batches and position from downstream analysis. First, I tried to do a parametric adjustment as follows:
``` combat_AAE_betas = ComBat(dat=edata, batch=batch, mod=NULL, par.prior=TRUE) ```
where ```batch = pheno$Sentrix_ID```
The batch effect was successfully corrected:
```
Found3batches
Adjusting for0covariate(s) or covariate level(s)
Found6352Missing Data Values 
Standardizing Data across genes
Fitting L/S model and finding priors
Finding parametric adjustments
Adjusting the Data
```
I then tried to run ComBat again with the obtained output, correcting for the row effect:
```
batch = pheno$Sentrix_row
edata = combat_AAE_betas
combat_AAE_betas <- ComBat(dat=edata, batch = batch, mod=NULL, par.prior = TRUE)
```
but this time the error occurred in the ```Standardizing Data across genes``` step:
```
Error in solve.default(crossprod(des), crossprod(des, y1)) : 
  Lapack routine dgesv: system is exactly singular: U[3,3] = 0
```
The batch and position variable are not colinear, I am not sure why I am getting the error when I am not supplying a model matrix. 

Thanks,
Maggie

**Comment by pstew** [comment]
In my case, this error was caused by missing data (NA's). Seems like you need at least two non-missing values per row (gene/protein) per batch.

**Comment by wondersandy** [comment]
In my case, when I subset my pheno object (traits/metadata object), I did it the usual way of subsetting a dataframe, which left the levels of traits the same as in old data frame. Using droplevels() to subset dataframe containing factor variables solved the problem for me.

**Comment by rorynolan** [comment]
If you have factors whose levels are absent, this can occur (the call to `model.matrix()` then creates a column of 0s). It's handy to run `forcats::fct_drop()` on your factors to fix this.

**Comment by snijesh** [comment]
Just change your data as as matrix

`data=as.matrix(data)`

**Comment by cmatKhan** [comment]
> I got the same stupid error and I solved it by converting the `data.frame` to a `matrix` datatype.
> 
> When you have something like this:
> `ComBat(dat=data, batch=batch, mod=mod1)`
> 
> Use this instead:
> `ComBat(dat=as.matrix(data), batch=batch, mod=mod1)`

I realize that rather than just posting this, I could figure out where it is in the codebase and make a pull request myself. But, that said, it seems like checking the data type of the inputs is a reasonable place to throw some more specific error messages. It would be nice to see that incorporated in the next update.

**Comment by ginnyintifa** [comment]
For me it is the missing values. as @pstew pointed out, it may require " Seems like you need at least two non-missing values per row (gene/protein) per batch."
And if you are processing TMT data, this will cause an issue, because TMT data often have missing value seen in the whole batch. So basically I am using only the genes without any missing value to put into the combat function. Alternatively can impute the data first and combat.

**Comment by m-kouhsar** [comment]
In my case, this error occurred when my batch was a factor with a large number of levels (e.g. plate location with >50 levels). So, instead of considering it as a factor, I converted it to numeric values (`batch=as.numeric(as.factor(myData$PlateLocation)`), and the problem was resolved.
